// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtELGZlhklf-7pu-eByjpvaoFdDpXcywI',
    appId: '1:238108079413:web:ae29437900ce9dbd06c87c',
    messagingSenderId: '238108079413',
    projectId: 'flutter-test-f1ed0',
    authDomain: 'flutter-test-f1ed0.firebaseapp.com',
    storageBucket: 'flutter-test-f1ed0.firebasestorage.app',
    measurementId: 'G-KBX1EZ8279',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCdXraMwgDRNVJA1ZSFcUfh990X51crCo',
    appId: '1:238108079413:android:ba8ad1d20e7bb26906c87c',
    messagingSenderId: '238108079413',
    projectId: 'flutter-test-f1ed0',
    storageBucket: 'flutter-test-f1ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDrMCueDIp04Pp_4b6DM4wS7LNoQiIjk',
    appId: '1:238108079413:ios:47f61a1680fe752406c87c',
    messagingSenderId: '238108079413',
    projectId: 'flutter-test-f1ed0',
    storageBucket: 'flutter-test-f1ed0.firebasestorage.app',
    iosBundleId: 'com.example.pruebaAerolinea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDrMCueDIp04Pp_4b6DM4wS7LNoQiIjk',
    appId: '1:238108079413:ios:47f61a1680fe752406c87c',
    messagingSenderId: '238108079413',
    projectId: 'flutter-test-f1ed0',
    storageBucket: 'flutter-test-f1ed0.firebasestorage.app',
    iosBundleId: 'com.example.pruebaAerolinea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtELGZlhklf-7pu-eByjpvaoFdDpXcywI',
    appId: '1:238108079413:web:ffa7187e81dad25b06c87c',
    messagingSenderId: '238108079413',
    projectId: 'flutter-test-f1ed0',
    authDomain: 'flutter-test-f1ed0.firebaseapp.com',
    storageBucket: 'flutter-test-f1ed0.firebasestorage.app',
    measurementId: 'G-JSBETJ5P2M',
  );
}
